print("row row row")
print(" your boat")
print("Gently down the stream.")
print("Merrily")
print("Life is but a dream.")
print("And I was like")
print("baby baby baby")
print("oooooooh!")
print("Baby")
print("oooooooh!")
